django_project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/",include('polls.urls'))
]

django_project/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
    path('name/',views.get_name),
    path('thanks/',views.thanks,name='thanks'),
    path('question_input/',views.question_input,name='question_input')

]

django_project/mysite/polls/models.py
from django.db import models
from django.utils import timezone
from django.forms import ModelForm

class Question(models.Model):
    question_text = models.CharField('问题',max_length=100)
    pub_date = models.DateTimeField('发布时间')

    def __str__(self):
        return self.question_text
    def __unicode__(self):
        return "123"
    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField('投票选项',max_length=100)
    votes = models.IntegerField('票数',default=0)

    def __str__(self):
        return self.choice_text 
    

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = '__all__'

django_project/mysite/polls/forms.py
from django import forms

class myform(forms.Form):
    user_name = forms.CharField(max_length=10,label='你的姓名',help_text='请输入您的姓名')
    age = forms.IntegerField(min_value=0,label='你的年龄',help_text='请输入您的年龄')
    address = forms.CharField(max_length=100,label='地址')

django_project/mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .models import Question,Choice,QuestionForm,ChoiceForm
from .forms import myform

def index(request):
    # context = {'message':'Hello,world!'}
    q = Question.objects.all()
    context = {'new_list':q}
    return render(request,'polls/index.html',context)

def detail(request, question_id):
    q = Question.objects.get(id=question_id)
    context = {'question':q}
    return render(request,'polls/detail.html',context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message':"你没有选择",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))
    
def question_input(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            q = form.save()
            q.save()
            return HttpResponseRedirect(reverse('polls:index'))
    else:
        form = QuestionForm()
        return render(request,'polls/question_input.html',{'form':form})

def get_name(request):
    if request.method == 'POST':
        form = myform(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/thanks/')
    else:
        form = myform()

    return render(request,'polls/name.html',{'form':form})

def thanks(request):
    return HttpResponse("你输入的是："+request.POST['user_name'])

django_project/mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <label for="choice{{ forloop.counter }}">{{ choice.votes }}</label>
            <br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

django_project/mysite/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if new_list %}
    <ul>
        {% for title in new_list %}
        <li><a href="{% url 'polls:detail' title.id %}">{{ title }}</a> {{ title.pub_date }}</li>
        {% endfor %}
    </ul>
{% else %}
<h2>没有新闻</h2>
{% endif %}

django_project/mysite/polls/templates/polls/name.html
<form action='{% url "polls:thanks" %}' method='POST'>
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="提交">
</form>

django_project/mysite/polls/templates/polls/question_input.html
<form action='?' method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交">
</form>

django_project/mysite/polls/templates/polls/results.html
<h1>投票结果</h1>

<h2>{{ question.question_text}}</h2>
<br>
{% for choice in question.choice_set.all %}
<li>{{ choice.id }}.{{ choice.choice_text }}：{{ choice.votes }}票<br></li>
{% endfor %}

<a href="{% url 'polls:detail' question.id %}">继续投票？</a>
<br>
<a href="{% url 'polls:index' %}">返回首页</a>